### ISSUE TITLE
Better Folder structure

### ISSUE THREAD

**Issue by victorferraz** [alexanmtz/react-native-ready#3]
Good job my friend I have some suggestions/questions:
Why are you not using `action`?
What about to create component folder, to modularize the code?
What about to move request logic to action folder?

**Comment by alexanmtz** [comment]
Hey @victorferraz , thanks! 

This first version I was doing the simplest possible, just in react and to have a more stable navigation component, that uses redux to dispatch navigation actions. Now that everything is set and running, I will do so, or we can do it together!

You're right about the component folder.

And we could move the request logic all to actions and have presentational and container components.

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/59

**Comment by alexandreramosdev** [comment]
@alexanmtz I belive that is important update the depecencies this projeto before I refator structure! Whats do you think this!

**Comment by alexandreramosdev** [comment]
![Screenshot_2019-06-25_01-40-27](https://user-images.githubusercontent.com/34720135/60069707-51c6af80-96ea-11e9-9998-493ef1feae77.png)

**Comment by alexanmtz** [comment]
Yeah @alexandreramosdev, I think will be great to update before so we can use the latest features 👌

**Comment by alexandreramosdev** [comment]
@alexanmtz Tive bastante problema para conseguir rodar o projeto em minha maquina! tentei muitas forma para resolver mas sem sucesso. tentei atualizar o projeto para ver se conseguia mas sem sucesso! 
Minha maquina é um Archlinux.
Eu pensei em instalar um expo atualizado e mover o codigo para este novo projeto em uma nova branch ou com o react-native mesmo pois da mais opções de config.

O que vc acha?

**Comment by alexanmtz** [comment]
Olá @alexandreramosdev , obrigado pelo retorno! Qual problema exatamente você tem quando tenta rodar? Para trabalhar fora do expo, acho que teríamos que dar um eject. Me diz qual o problema e você pode fazer uma tentativa rápida de mover para puro react-native e testar para ver se é problema com o expo no linux.

**Comment by alexandreramosdev** [comment]
São vario errors que dão!  Mas nao foi o expo no linux!  Eu pensei nisso ai eu iniciei um projeto novo com expo para fazer um teste. E foi de boa!
Acredito foi que o expo 33 mudou muita coisa e o projeto esta no expo 28 esta bastante defazado e quebou muito package!  nao rodou nem o inicial !

**Comment by alexandreramosdev** [comment]
Vou iniciar a mover para o react-native hoje mesmo! Como são pouco codigo acredito 2 dia o projeto ja esteja rodando

**Comment by alexanmtz** [comment]
Beleza @alexandreramosdev , vamos seguir assim então e abrimos outra issue posteriormente para ver o caso do expo no linux e atualizar as versões necessárias. Muito obrigado 🙏

**Comment by alexandreramosdev** [comment]
@alexanmtz movi o projeto para react-native ficou muito bom! 

O projeto ficou bem menos verboso e de facil compeensão! Neste estado nao foi necessario utilizar redux para centralizar os dados! Porem caso o projeto cresça pode usar o redux com duck patter é um bom e escalavei!

Adicionai o eslint e editorconfig para uma padronização do codigo assim evitar pequenos bug! como aquela ponto e virgula que agente esquemos de vez enquando. 

Disto isso gaotei muito de participar e gostaria muito de continuar a colaborar neste projeto! me diz ai quais os novos passos.

> sugestao para novo update no projeto é add styled-components para separar o estilos da logica nos files.

Confira meu pull request
 PR #6

**Comment by alexanmtz** [comment]
Legal @alexandreramosdev , fico feliz que tenha gostado do projeto. A idéia do expo era facilitar, mas de fato está causando mais dor de cabeça que benefícios. Vamos seguir com React Native puro.

Sobre os reducers, o projeto é o básico para começar e será extendido por quem for usar, então é importante ter já uma estrutura e organização mesmo com poucas requisições ainda, então precisamos criar reducers mesmo com pouco uso.

**Comment by alexandreramosdev** [comment]
Sem problema! irei adicionar o redux com duck pattern

**Comment by alexanmtz** [comment]
Thanks for the great contribution @alexandreramosdev 🎉
